In [116]:
import pandas as pd

file_data = pd.read_csv("./Resources/Final_Global Dataset of Inflation.csv", encoding="latin1")
file_data

,Unnamed: 0.1,Unnamed: 0,country code,inflation_type,country,2005,2006,2007,2008,2009,...,2012,2013,2014,2015,2016,2017,2018,2019,2021,2022
0,0,0,ABW,Headline Consumer Price Inflation,Aruba,3.40,3.61,5.39,8.96,-2.14,...,0.63,-2.37,0.42,0.48,-0.89,-0.47,3.58,4.26,0.74,6.04
1,1,2,AGO,Headline Consumer Price Inflation,Angola,22.96,13.31,12.25,12.47,13.72,...,10.28,8.78,7.30,9.16,32.38,29.84,19.63,17.08,23.85,21.35
2,2,3,ALB,Headline Consumer Price Inflation,Albania,2.36,2.41,2.91,3.41,2.29,...,2.03,1.93,1.62,1.91,1.29,1.99,2.03,1.41,2.04,6.73
3,3,4,ARE,Headline Consumer Price Inflation,United Arab Emirates,6.20,9.28,11.13,12.27,1.57,...,0.66,1.09,2.34,4.07,1.62,1.97,3.06,-1.93,0.18,5.22
4,4,5,ARG,Headline Consumer Price Inflation,Argentina,9.64,10.90,8.83,8.59,6.27,...,10.04,10.62,38.08,26.54,39.40,25.68,34.28,53.55,48.41,72.43
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
422,422,546,VEN,Food Consumer Price Inflation,"Venezuela, RB",21.14,20.07,26.83,42.82,27.96,...,24.80,54.15,86.73,218.67,217.74,482.70,38386.00,17710.79,1934.56,193.71
423,423,548,VNM,Food Consumer Price Inflation,Vietnam,11.08,8.68,11.23,36.89,8.46,...,7.90,2.69,4.00,1.48,2.61,-1.08,3.24,4.07,0.73,1.96
424,424,552,ZAF,Food Consumer Price Inflation,South Africa,2.00,6.10,9.51,15.31,9.53,...,7.15,5.70,7.60,5.12,10.53,6.95,3.58,3.55,6.10,8.97
425,425,553,ZMB,Food Consumer Price Inflation,Zambia,18.60,4.90,5.30,13.80,14.20,...,7.01,6.52,7.25,11.08,21.26,5.76,7.14,10.44,27.71,15.68
426,426,554,ZWE,Food Consumer Price Inflation,Zimbabwe,223.90,1034.20,7375.30,7375.30,-15.08,...,4.62,1.69,-3.12,-3.34,-3.26,2.50,14.59,86.12,105.80,63.31

In [117]:
file_data = file_data.rename(columns = {"2005":"year_2005","2006":"year_2006","2007":"year_2007","2008":"year_2008","2009":"year_2009","2010":"year_2010","2011":"year_2011","2012":"year_2012","2013":"year_2013","2014":"year_2014","2015":"year_2015","2016":"year_2016","2017":"year_2017","2018":"year_2018","2019":"year_2019","2020":"year_2020","2021":"year_2021","2022":"year_2022" })
file_data

,Unnamed: 0.1,Unnamed: 0,country code,inflation_type,country,year_2005,year_2006,year_2007,year_2008,year_2009,...,year_2012,year_2013,year_2014,year_2015,year_2016,year_2017,year_2018,year_2019,year_2021,year_2022
0,0,0,ABW,Headline Consumer Price Inflation,Aruba,3.40,3.61,5.39,8.96,-2.14,...,0.63,-2.37,0.42,0.48,-0.89,-0.47,3.58,4.26,0.74,6.04
1,1,2,AGO,Headline Consumer Price Inflation,Angola,22.96,13.31,12.25,12.47,13.72,...,10.28,8.78,7.30,9.16,32.38,29.84,19.63,17.08,23.85,21.35
2,2,3,ALB,Headline Consumer Price Inflation,Albania,2.36,2.41,2.91,3.41,2.29,...,2.03,1.93,1.62,1.91,1.29,1.99,2.03,1.41,2.04,6.73
3,3,4,ARE,Headline Consumer Price Inflation,United Arab Emirates,6.20,9.28,11.13,12.27,1.57,...,0.66,1.09,2.34,4.07,1.62,1.97,3.06,-1.93,0.18,5.22
4,4,5,ARG,Headline Consumer Price Inflation,Argentina,9.64,10.90,8.83,8.59,6.27,...,10.04,10.62,38.08,26.54,39.40,25.68,34.28,53.55,48.41,72.43
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
422,422,546,VEN,Food Consumer Price Inflation,"Venezuela, RB",21.14,20.07,26.83,42.82,27.96,...,24.80,54.15,86.73,218.67,217.74,482.70,38386.00,17710.79,1934.56,193.71
423,423,548,VNM,Food Consumer Price Inflation,Vietnam,11.08,8.68,11.23,36.89,8.46,...,7.90,2.69,4.00,1.48,2.61,-1.08,3.24,4.07,0.73,1.96
424,424,552,ZAF,Food Consumer Price Inflation,South Africa,2.00,6.10,9.51,15.31,9.53,...,7.15,5.70,7.60,5.12,10.53,6.95,3.58,3.55,6.10,8.97
425,425,553,ZMB,Food Consumer Price Inflation,Zambia,18.60,4.90,5.30,13.80,14.20,...,7.01,6.52,7.25,11.08,21.26,5.76,7.14,10.44,27.71,15.68
426,426,554,ZWE,Food Consumer Price Inflation,Zimbabwe,223.90,1034.20,7375.30,7375.30,-15.08,...,4.62,1.69,-3.12,-3.34,-3.26,2.50,14.59,86.12,105.80,63.31

In [118]:
file_data

,Unnamed: 0.1,Unnamed: 0,country code,inflation_type,country,year_2005,year_2006,year_2007,year_2008,year_2009,...,year_2012,year_2013,year_2014,year_2015,year_2016,year_2017,year_2018,year_2019,year_2021,year_2022
0,0,0,ABW,Headline Consumer Price Inflation,Aruba,3.40,3.61,5.39,8.96,-2.14,...,0.63,-2.37,0.42,0.48,-0.89,-0.47,3.58,4.26,0.74,6.04
1,1,2,AGO,Headline Consumer Price Inflation,Angola,22.96,13.31,12.25,12.47,13.72,...,10.28,8.78,7.30,9.16,32.38,29.84,19.63,17.08,23.85,21.35
2,2,3,ALB,Headline Consumer Price Inflation,Albania,2.36,2.41,2.91,3.41,2.29,...,2.03,1.93,1.62,1.91,1.29,1.99,2.03,1.41,2.04,6.73
3,3,4,ARE,Headline Consumer Price Inflation,United Arab Emirates,6.20,9.28,11.13,12.27,1.57,...,0.66,1.09,2.34,4.07,1.62,1.97,3.06,-1.93,0.18,5.22
4,4,5,ARG,Headline Consumer Price Inflation,Argentina,9.64,10.90,8.83,8.59,6.27,...,10.04,10.62,38.08,26.54,39.40,25.68,34.28,53.55,48.41,72.43
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
422,422,546,VEN,Food Consumer Price Inflation,"Venezuela, RB",21.14,20.07,26.83,42.82,27.96,...,24.80,54.15,86.73,218.67,217.74,482.70,38386.00,17710.79,1934.56,193.71
423,423,548,VNM,Food Consumer Price Inflation,Vietnam,11.08,8.68,11.23,36.89,8.46,...,7.90,2.69,4.00,1.48,2.61,-1.08,3.24,4.07,0.73,1.96
424,424,552,ZAF,Food Consumer Price Inflation,South Africa,2.00,6.10,9.51,15.31,9.53,...,7.15,5.70,7.60,5.12,10.53,6.95,3.58,3.55,6.10,8.97
425,425,553,ZMB,Food Consumer Price Inflation,Zambia,18.60,4.90,5.30,13.80,14.20,...,7.01,6.52,7.25,11.08,21.26,5.76,7.14,10.44,27.71,15.68
426,426,554,ZWE,Food Consumer Price Inflation,Zimbabwe,223.90,1034.20,7375.30,7375.30,-15.08,...,4.62,1.69,-3.12,-3.34,-3.26,2.50,14.59,86.12,105.80,63.31

In [119]:
file_data.to_csv('Official_Global Dataset of Inflation.csv')

In [121]:
file_data = pd.read_csv("./Output/Official_Global Dataset of Inflation.csv", encoding="latin1")
file_data

,country code,inflation_type,country,year_2005,year_2006,year_2007,year_2008,year_2009,year_2010,year_2011,year_2012,year_2013,year_2014,year_2015,year_2016,year_2017,year_2018,year_2019,year_2021,year_2022
0,ABW,Headline Consumer Price Inflation,Aruba,3.40,3.61,5.39,8.96,-2.14,2.08,4.32,0.63,-2.37,0.42,0.48,-0.89,-0.47,3.58,4.26,0.74,6.04
1,AGO,Headline Consumer Price Inflation,Angola,22.96,13.31,12.25,12.47,13.72,14.48,13.48,10.28,8.78,7.30,9.16,32.38,29.84,19.63,17.08,23.85,21.35
2,ALB,Headline Consumer Price Inflation,Albania,2.36,2.41,2.91,3.41,2.29,3.57,3.41,2.03,1.93,1.62,1.91,1.29,1.99,2.03,1.41,2.04,6.73
3,ARE,Headline Consumer Price Inflation,United Arab Emirates,6.20,9.28,11.13,12.27,1.57,0.88,0.88,0.66,1.09,2.34,4.07,1.62,1.97,3.06,-1.93,0.18,5.22
4,ARG,Headline Consumer Price Inflation,Argentina,9.64,10.90,8.83,8.59,6.27,10.46,9.77,10.04,10.62,38.08,26.54,39.40,25.68,34.28,53.55,48.41,72.43
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
422,VEN,Food Consumer Price Inflation,"Venezuela, RB",21.14,20.07,26.83,42.82,27.96,32.97,29.92,24.80,54.15,86.73,218.67,217.74,482.70,38386.00,17710.79,1934.56,193.71
423,VNM,Food Consumer Price Inflation,Vietnam,11.08,8.68,11.23,36.89,8.46,11.41,26.69,7.90,2.69,4.00,1.48,2.61,-1.08,3.24,4.07,0.73,1.96
424,ZAF,Food Consumer Price Inflation,South Africa,2.00,6.10,9.51,15.31,9.53,1.37,7.13,7.15,5.70,7.60,5.12,10.53,6.95,3.58,3.55,6.10,8.97
425,ZMB,Food Consumer Price Inflation,Zambia,18.60,4.90,5.30,13.80,14.20,5.20,4.83,7.01,6.52,7.25,11.08,21.26,5.76,7.14,10.44,27.71,15.68
426,ZWE,Food Consumer Price Inflation,Zimbabwe,223.90,1034.20,7375.30,7375.30,-15.08,3.83,3.99,4.62,1.69,-3.12,-3.34,-3.26,2.50,14.59,86.12,105.80,63.31

In [74]:
!pip install psycopg2

Requirement already satisfied: psycopg2 in c:\users\lopri\anaconda3\lib\site-packages (2.9.6)

In [75]:
from sqlalchemy import create_engine

In [14]:
from config import username, password, hostname, port, db


# username = "postgres"
# password = "2d9c92d9c9"
# hostname = "localhost"
# port = "5432"
# db = "project_3"



engine = create_engine(f'postgresql+psycopg2://{username}:{password}@{hostname}:{port}/{db}')

ImportError: cannot import name 'username' from 'config' (C:\Users\lopri\All Things Class Related\Gloabl Inflation\config.py)